customer/urls.py
from django.conf.urls import url

from . import views
from django.conf.urls.static import static
from django.urls import reverse

app_name = 'customer'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^summary/$', views.profile_summary, name='summary'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^files/$', views.company_files, name='files'),

    # url(r'^$', views.index),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^company/list/$', views.CompanyList.as_view(), name='company_list'),
    # url(r'^company/create/$', views.CompanyCreate.as_view(), name='company_create'),
    # url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyUpdate.as_view(), name='company_update'),
    url(r'^company$', views.CompanyView.as_view(), name='company'),


    # employee urls
    url(r'^employee/list/$', views.EmployeeList.as_view(), name='employee_list'),
    url(r'^employee/(?P<pk>[0-9]+)/$', views.EmployeeUpdate.as_view(), name='employee_update'),
    url(r'^employee/create/$', views.EmployeeCreate.as_view(), name='employee_create'),

    # product urls
    url(r'^product/list/$', views.ProductList.as_view(), name='product_list'),
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductUpdate.as_view(), name='product_update'),
    url(r'^prod/(?P<product_id>[0-9]+)/$', views.product_edit, name='prod_update'),
    url(r'^product/create/$', views.ProductCreate.as_view(), name='product_create'),
    url(r'^product/detail/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name='product_detail'),

    url(r'^order/list/$', views.OrderList.as_view(), name='order_list'),
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderUpdate.as_view(), name='order_update'),
    url(r'^order/create/$', views.OrderCreate.as_view(), name='order_create'),

    url(r'^order/discuss/list/$', views.OrderDiscussList.as_view(), name='order_discuss_list'),
    url(r'^order/discuss/(?P<pk>[0-9]+)/$', views.order_discuss, name='order_discuss'),


    url(r'^site/(?P<path>.*)$', views.site_index, name='site_index'),


]

mtplus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mtplus.views import HomePageView, ContactPageView, FaqPageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^contact/$', ContactPageView.as_view(), name='contact'),
    url(r'^faq/$', FaqPageView.as_view(), name='faq'),
    url(r'^customer/', include('customer.urls')),
    url(r'^admin/', admin.site.urls),
    url(r"^account/", include("account.urls")),
    url(r'^files/', include('filer.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/views.py
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, ListView, FormView
from django.contrib import messages
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _

from customer.forms import OrderForm, CompanyForm, ProfileForm, ProductForm, ProductFormSet, CompanyFormSet

from customer.models import Company, Employee, Product, Order, OrderDiscuss, OrderDiscussMessage, File, CompanyFile
from mtplus.views import FormsetUpdateView


class IndexView(generic.ListView):
    # template_name = 'index.html'
    context_object_name = 'product_list'
    model = Product
    template_name = 'customer/pub_product_list.html'

    def get_queryset(self):
        # Get list of customers
        search = self.request.GET.get('search')
        if search is not None and search != '':
            return Product.objects.filter(name__icontains=search).order_by('name')
        else:
            return Product.objects.order_by('name')


class ProductDetail(generic.DetailView):
 model = Product
 template_name = 'customer/pub_product_detail.html'

# class DetailView(FormView):
# template_name = 'customer/company_form.html'
# form_class = CustomerForm
# def form_valid(self, form):
# # this method is called when valid form data has been POSTed.
# # it should return an HttpResponse
# return super(DetailView, self).form_valid(form)

class CompanyCreate(FormView):
    form_class = CompanyForm
    template_name = 'customer/company_form.html'
    success_url = reverse_lazy('customer:company_list')


# class CompanyCreate(CreateView):
# model = Company
# fields = ('__all__')
#     success_url = reverse_lazy('customer:company_list')
# template_name = 'customer/company_form.html'


class CompanyUpdate(LoginRequiredMixin, UpdateView):
    model = Company
    fields = ('__all__')
    success_url = reverse_lazy('customer:company_list')
    # template_name = 'customer/company_form.html'


class CompanyList(LoginRequiredMixin, ListView):
    model = Company
    template = 'customer/company_list.html'


class EmployeeUpdate(LoginRequiredMixin, UpdateView):
    model = Employee
    fields = ('__all__')
    success_url = reverse_lazy('customer:employee_list')
    # template_name = 'customer/employee_form.html'


class EmployeeCreate(LoginRequiredMixin, CreateView):
    model = Employee
    fields = ('__all__')
    success_url = reverse_lazy('customer:employee_list')
    # template_name = 'customer/employee_form.html'


class EmployeeList(LoginRequiredMixin, ListView):
    model = Employee
    template_name = 'customer/employee_list.html'


class ProductUpdate(LoginRequiredMixin, FormsetUpdateView):
    form_class = ProductForm
    model = Product
    success_url = reverse_lazy('customer:product_list')
    template_name = 'customer/product_form.html'
    formset_class = ProductFormSet



    #
    # def form_valid(self, form):
    #     cur_company = self.get_object()
    #     print('product id=%s' % cur_company.id)
    #     for each in form.cleaned_data['images']:
    #         ProductImage.objects.create(product=cur_company, image=each)
    #     return super().form_valid(form)


class ProductCreate(ProductUpdate):
    # form_class = ProductForm
    # model = Product
    # success_url = reverse_lazy('customer:product_list')
    # template_name = 'customer/product_form.html'
    # formset_class = ProductFormSet

    def get_object(self):
        if self.request.user.employee:
            product = Product()
            product.company = self.request.user.employee.company
            print('get object %s' % (product.company.name))
            return product
        else:
            raise ImproperlyConfigured(
                "No Employee model associated with user.")


class ProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'customer/product_list.html'


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'customer/order_list.html'


class OrderCreate(LoginRequiredMixin, CreateView):
    form_class = OrderForm
    model = Order
    # fields = ('__all__')
    success_url = reverse_lazy('customer:order_list')
    template_name = 'customer/order_form.html'


class OrderUpdate(LoginRequiredMixin, UpdateView):
    form_class = OrderForm
    model = Order
    # fields = ('__all__')
    success_url = reverse_lazy('customer:order_list')
    template_name = 'customer/order_form.html'


class OrderDiscussList(LoginRequiredMixin, ListView):
    model = OrderDiscuss
    template_name = 'customer/order_discuss_list.html'



def get_field(dict, key):
    try:
        return dict[key]
    except:
        return None


@login_required
def order_discuss(request, pk):
    order_disc = OrderDiscuss.objects.filter(order_id=pk)[0]
    if request.method == 'POST':
        if get_field(request.POST, 'message'):
            order_disc_msg = OrderDiscussMessage(message=get_field(request.POST, 'message'),
                                                 created_by=get_current_user(request))
            order_disc_msg.save()
            order_disc.messages.add(order_disc_msg)
            order_disc.save()
        elif get_field(request.FILES, 'file'):
            f = get_field(request.FILES, 'file')
            file_model = File(name=f.name, file=f)
            file_model.save()
            order_disc.order_files.add(file_model)
            order_disc.save()
    return render(request, 'customer/chat.html',
                  {'order_disc': order_disc, })


def get_current_user(request):
    if request.user.is_authenticated:
        return User.objects.get(username=request.user.username)
    else:
        return None;


def site_index(request, path):
    return render(request, path)


@login_required
def profile_summary(request):
    return render(request, "customer/summary.html")


@login_required
def company_files(request):
    return render(request, "customer/company_files.html")


class ProfileView(LoginRequiredMixin, FormView):
    template_name = "customer/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy('customer:summary')
    messages = {
        "profile_updated": {
            "level": messages.SUCCESS,
            "text": _("Account profile updated.")
        },
    }

    def get_form_class(self):
        # @@@ django: this is a workaround to not having a dedicated method
        # to initialize self with a request in a known good state (of course
        # this only works with a FormView)
        # self.primary_email_address = EmailAddress.objects.get_primary(self.request.user)
        return super(ProfileView, self).get_form_class()

    def get_initial(self):
        initial = super(ProfileView, self).get_initial()
        initial["last_name"] = self.request.user.last_name
        initial["first_name"] = self.request.user.first_name
        initial["middle_name"] = self.request.user.middle_name
        initial["phone"] = self.request.user.phone
        if hasattr(self.request.user, 'employee'):
            initial["dob"] = self.request.user.employee.dob
            initial["sex"] = self.request.user.employee.sex
            initial["company"] = self.request.user.employee.company
            initial["job_position"] = self.request.user.employee.job_position
            initial["certificates"] = self.request.user.employee.certificates

        return initial

    # def post(self, request, *args, **kwargs): 
    #     form = self.get_form()
    #     if form.is_valid():
    #         print('valid form')
    #         return self.form_valid(form)
    #     else:
    #         print('invalid form, %s\n%s'%(form.cleaned_data,form.errors))
    #         return self.form_invalid(form)     

    def form_valid(self, form):
        print('form valid')
        self.update_profile(form)
        if self.messages.get("profile_updated"):
            messages.add_message(
                self.request,
                self.messages["profile_updated"]["level"],
                self.messages["profile_updated"]["text"]
            )
        # return redirect(self.get_success_url())
        return super(ProfileView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super(ProfileView, self).get_context_data(**kwargs)
        return ctx

    def update_profile(self, form):
        self.update_user(form)
        self.update_employee(form)

    def update_user(self, form):
        fields = {}
        if "first_name" in form.cleaned_data:
            fields["first_name"] = form.cleaned_data["first_name"]
        if "last_name" in form.cleaned_data:
            fields["last_name"] = form.cleaned_data["last_name"]
        if "middle_name" in form.cleaned_data:
            fields["middle_name"] = form.cleaned_data["middle_name"]
        if "phone" in form.cleaned_data:
            fields["phone"] = form.cleaned_data["phone"]
        if fields:
            user = self.request.user
            for k, v in fields.items():
                print('setting values %s=%s' % (k, v))
                setattr(user, k, v)
            user.save()

    def update_employee(self, form):
        fields = {}
        if "dob" in form.cleaned_data:
            fields["dob"] = form.cleaned_data["dob"]
        if "sex" in form.cleaned_data:
            fields["sex"] = form.cleaned_data["sex"]
        if "job_position" in form.cleaned_data:

customer/templates/customer/company_form.html
{% extends "mtplus/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% block breadcrumbs_title %}{% block breadcrumbs_current_title %}{% trans 'My Company' %}{% endblock %}{% endblock %}{% endblock %}


{% load thumbnail %}


{% block main_content %}
    <div class="row">
        <div class="col-lg-12">
            <form  id="companyForm" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% crispy form %}
            </form>
{#            <img src="{{ company.logo.avatar.url }}" alt="" />#}
        </div>
    </div>
{% endblock %}


customer/templates/customer/company_list.html
{% extends "layout_2_col_profile.html" %}
{% load i18n %}

{% block title %}
    {{ flatpage.title }} | {{ block.super }}
{% endblock %}

{% block header %}
    <div class="page-header action">

        <h1>{{ flatpage.title }}</h1>
    </div>
{% endblock %}


{% block tabcontent %}
    {% if object_list %}
        <table class="table table-striped table-bordered">
            <tbody>
            <tr>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'Address' %}</th>
                <th>{% trans 'Founded' %}</th>
                <th>{% trans 'Employee amount' %}</th>
                <th>{% trans 'Production power' %}</th>
                <th>{% trans 'Action' %}</th>
            </tr>
            {% for company in object_list %}
                <tr>
                    <td><a href="{% url 'customer:company_update' pk=company.id %}">{{ company.name }}</a></td>
                    <td>{{ company.company_type }}</td>
                    <td>{{ company.address }}</td>
                    <td>{{ company.foundation_date }}</td>
                    <td>{{ company.employees_amount }}</td>
                    <td>{{ company.production_power }}</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-default"
                               href="{% url 'customer:company_update' pk=company.id %}">{% trans 'View' %}</a>
                            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'customer:company_update' pk=company.id %}">
                                        {% trans 'Wish list settings' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'customer:company_update' pk=company.id %}">
                                        {% trans 'Delete' %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include "partials/pagination.html" %}
    {% else %}
        <p>
            {% trans "You don't have any partners lists yet." %}
        </p>
    {% endif %}

    <p>
        <a href="{% url 'customer:company_create' %}" class="btn btn-primary">{% trans 'Create Partner' %}</a>
        <a href="{% url 'customer:index' %}">All</a>
    </p>

{% endblock tabcontent %}

customer/templates/customer/employee_form.html
{% extends "layout_2_col_profile.html" %}
{% load i18n %}

{% block title %}{% block breadcrumbs_title %}{% block breadcrumbs_current_title %}{% trans 'Employee' %}{% endblock %}{% endblock %}{% endblock %}



{% block header %}
    <div class="page-header action">

        <h1>{{ company.name }}</h1>
    </div>
{% endblock %}


{% block tabcontent %}
    {% include 'partials/form.html' with form_id="employee_form" action="." %}
    <a href="{% url 'customer:employee_list' %}">List</a>
    <a href="{% url 'customer:index' %}">All</a>
{% endblock tabcontent %}


customer/templates/customer/order_discuss_list.html
{% extends "layout_2_col_profile.html" %}
{% load i18n %}

{% block title %}
    {{ flatpage.title }} | {{ block.super }}
{% endblock %}

{% block header %}
    <div class="page-header action">

        <h1>{{ flatpage.title }}</h1>
    </div>
{% endblock %}


{% block tabcontent %}
    {% if object_list %}
        <table class="table table-striped table-bordered">
            <tbody>
            <tr>
                <th>{% trans 'Order' %}</th>
                <th>{% trans 'Participants' %}</th>
                <th>{% trans 'Messages' %}</th>
                <th>{% trans 'Action' %}</th>
            </tr>
            {% for order_disc in object_list %}
                <tr>
                    <td><a href="{% url 'customer:order_discuss' pk=order_disc.id %}">{{ order_disc.order.number }}</a></td>
                    <td>{{ order_disc.participants.all.count }}</td>
                    <td>{{ order_disc.messages.all.count }}</td>
                  <td>
                        <div class="btn-group">
                            <a class="btn btn-default"
                               href="{% url 'customer:order_discuss' pk=order_disc.id %}">{% trans 'View' %}</a>
                            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'customer:order_discuss' pk=order_disc.id %}">
                                        {% trans 'Wish list settings' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'customer:order_discuss' pk=order_disc.id %}">
                                        {% trans 'Delete' %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include "partials/pagination.html" %}
    {% else %}
        <p>
            {% trans "You don't have any products lists yet." %}
        </p>
    {% endif %}

    <p>
        <a href="{% url 'customer:product_create' %}" class="btn btn-primary">{% trans 'Create Product' %}</a>
        <a href="{% url 'customer:index' %}">All</a>
    </p>

{% endblock tabcontent %}

customer/templates/customer/order_form.html
{% extends "mtplus/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block title %}{% block breadcrumbs_title %}{% block breadcrumbs_current_title %}{{ form.number.value|default:"New order" }}{% endblock %}{% endblock %}{% endblock %}



{% block main_content %}
    <div class="row">
        <div class="col-lg-12">
            {#            <div class="tabs-container">#}
            {% crispy form %}
            {#            </div>#}
        </div>
    </div>
{% endblock %}

customer/templates/customer/order_list.html
{% extends "mtplus/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}{% block breadcrumbs_title %}{% block breadcrumbs_current_title %}{% trans 'Orders' %}{% endblock %}{% endblock %}{% endblock %}



{% block main_content %}

            <div class="ibox-content m-b-sm border-bottom">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="order_id">{% trans 'Order ID' %}</label>
                            <input type="text" id="order_id" name="order_id" value="" placeholder="Order ID" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="status">{% trans 'Order status' %}</label>
                            <input type="text" id="status" name="status" value="" placeholder="Status" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="customer">{% trans 'Customer' %}</label>
                            <input type="text" id="customer" name="customer" value="" placeholder="Customer" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="date_added">{% trans 'Date added' %}</label>
                            <div class="input-group date">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input id="date_added" type="text" class="form-control" value="03/04/2014">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="date_modified">{% trans 'Date modified' %}</label>
                            <div class="input-group date">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input id="date_modified" type="text" class="form-control" value="03/06/2014">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="control-label" for="amount">{% trans 'Amount' %}</label>
                            <input type="text" id="amount" name="amount" value="" placeholder="Amount" class="form-control">
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                 <div class="col-lg-12">
                        <div class=" controls btn-group">
                        <a href="{% url 'customer:order_create'  %}">
                            <button class="btn">{% trans 'Create' %}</button></a>
                   <a href="{% url 'customer:order_create' %}">
                        <button class="btn btn-primary">{% trans 'Search' %}</button> </a>
                        </div>   
                </div>
           </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-content">

                            <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                                <thead>
                                <tr>

                                    <th>{% trans 'Order ID' %}</th>
                                    <th data-hide="phone">{% trans 'Product' %}</th>
                                    <th data-hide="phone">{% trans 'Customer' %}</th>
                                    <th data-hide="phone">{% trans 'Amount' %}</th>
                                    <th data-hide="phone,tablet" >{% trans 'Date added' %}</th>
                                    <th data-hide="phone">{% trans 'Status' %}</th>
                                    <th class="text-right">{% trans 'Action' %}</th>

                                </tr>
                                </thead>
                                <tbody>
                                          {% for order in object_list %}
                                 <tr>
                    <td>{{ order.number }}</td>
                    <td>{{ order.product.name }}</td>
                    <td>{{ order.customer.full_name }}</td>
                    <td>{{ order.order_amount }} / {{ order.order_amount_unit }}</td>
                    
                    <td>{{ order.created_on }}</td>
                    <td> 
                    <span class="label label-primary">{{ order.status }}</span>
                    </td>
                   <td class="text-right">
                        <div class="btn-group">
                        <a href="{% url 'customer:order_update' pk=order.id %}">
                            <button class="btn-white btn btn-xs">{% trans 'View' %}</button></a>
                   <a href="{% url 'customer:order_update' pk=order.id %}">
                        <button class="btn-white btn btn-xs">{% trans 'Edit' %}</button> </a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
                    


                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="7">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

customer/templates/customer/product_form.html
{% extends "mtplus/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{% block breadcrumbs_title %}{% block breadcrumbs_current_title %}{{ form.name.value|default:"New product" }}{% endblock %}{% endblock %}{% endblock %}


{% block main_content %}
    <div class="row">
        <div class="col-lg-12">
{#            {{ form.errors }}#}
{#            {{ formset.errors }}#}
{#            {{ errors }}#}
            <form id="productForm" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

customer/templates/customer/pub_product_detail.html
{% extends user.is_authenticated|yesno:"mtplus/layout.html,mtplus/site_layout_base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}{% block breadcrumbs_title %}{% block breadcrumbs_current_title %}{{ product.name }}{% endblock %}{% endblock %}{% endblock %}
{% block breadcrumbs_sub %}
    <li><a href="{% url "customer:index" %}">{{ product.category.name }}</a></li>
{% endblock %}
{% block main_content %}
  <div class="row">
                <div class="col-lg-12">

                    <div class="ibox product-detail">
                        <div class="ibox-content">

                            <div class="row">
                                <div class="col-md-5">
                                    <div class="product-images">
                                    	{% if product.images %}
                                    	{% for images in product.images.all %}
                                        <div>
                                            <div class="image-imitation" style="padding:0px; " >
                                            	<!-- background:center no-repeat url('{{images.image.url}}') -->
                                                <img style="widgh:280px;height:280px" src="{{images.image.url}}" alt="">
                                            </div>
                                        </div>
                                        {% endfor %}
                                        {% endif %}

                                    </div>

                                </div>
                                <div class="col-md-7">

                                    <h2 class="font-bold m-b-xs">
                                       {{product.name}}
                                    </h2>
                                    <!-- <small>Many desktop publishing packages and web page editors now.</small> -->
                                    <div class="m-t-md">
                                        <h2 class="product-main-price">{{product.price}} {{product.currency}} / {{product.amount}} {{product.unit}} <small class="text-muted">{% trans 'Exclude Tax' %}</small> </h2>
                                    </div>
                                    <hr>

                                    <h4>{% trans 'Product description' %}</h4>

                                    <div class="small text-muted">
                                        {{product.notes|linebreaksbr}}

                                    <div>
                                        <div class="btn-group">
                                            <!-- <button class="btn btn-primary btn-sm"><i class="fa fa-cart-plus"></i> Add to cart</button> -->
                                            <button class="btn  btn-primary btn-sm"><i class="fa fa-star"></i> {% trans 'Add to wishlist' %} </button>
                                            <button class="btn btn-white btn-sm"><i class="fa fa-envelope"></i> {% trans 'Contact with author' %} </button>
                                        </div>
                                    </div>



                                </div>
                            </div>

                        </div>
                         <div class="ibox-footer"></div>

                    </div>

                </div>
            </div>
</div>
{% endblock %}

{% block extracss %}
	{{block.super}}
    <link href="{% static "mtplus/css/plugins/slick/slick.css" %}" rel="stylesheet">
    <link href="{% static "mtplus/css/plugins/slick/slick-theme.css" %}" rel="stylesheet">


{% endblock %}

{% block extrascript %}
	{{block.super}}
	<!-- slick carousel-->
    <script src="{% static "mtplus/js/plugins/slick/slick.min.js" %}"></script>
<script>
    $(document).ready(function(){


        $('.product-images').slick({
            dots: true
        });

    });

</script>
{% endblock %}