customer/urls.py
from django.conf.urls import url

from . import views
from django.conf.urls.static import static
from django.urls import reverse

app_name = 'customer'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^summary/$', views.profile_summary, name='summary'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^files/$', views.company_files, name='files'),

    # url(r'^$', views.index),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^company/list/$', views.CompanyList.as_view(), name='company_list'),
    # url(r'^company/create/$', views.CompanyCreate.as_view(), name='company_create'),
    # url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyUpdate.as_view(), name='company_update'),
    url(r'^company$', views.CompanyView.as_view(), name='company'),


    # employee urls
    url(r'^employee/list/$', views.EmployeeList.as_view(), name='employee_list'),
    url(r'^employee/(?P<pk>[0-9]+)/$', views.EmployeeUpdate.as_view(), name='employee_update'),
    url(r'^employee/create/$', views.EmployeeCreate.as_view(), name='employee_create'),

    # product urls
    url(r'^product/list/$', views.ProductList.as_view(), name='product_list'),
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductUpdate.as_view(), name='product_update'),
    url(r'^prod/(?P<product_id>[0-9]+)/$', views.product_edit, name='prod_update'),
    url(r'^product/create/$', views.ProductCreate.as_view(), name='product_create'),
    url(r'^product/detail/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name='product_detail'),

    url(r'^order/list/$', views.OrderList.as_view(), name='order_list'),
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderUpdate.as_view(), name='order_update'),
    url(r'^order/create/$', views.OrderCreate.as_view(), name='order_create'),

    url(r'^order/discuss/list/$', views.OrderDiscussList.as_view(), name='order_discuss_list'),
    url(r'^order/discuss/(?P<pk>[0-9]+)/$', views.order_discuss, name='order_discuss'),


    url(r'^site/(?P<path>.*)$', views.site_index, name='site_index'),


]

mtplus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mtplus.views import HomePageView, ContactPageView, FaqPageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^contact/$', ContactPageView.as_view(), name='contact'),
    url(r'^faq/$', FaqPageView.as_view(), name='faq'),
    url(r'^customer/', include('customer.urls')),
    url(r'^admin/', admin.site.urls),
    url(r"^account/", include("account.urls")),
    url(r'^files/', include('filer.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mtplus/views.py
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from django.views.generic import UpdateView

from django.views.generic.base import TemplateView
from django.contrib import messages


class HomePageView(TemplateView):
    template_name = 'landing/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # messages.info(self.request, 'Info: Hello')
        # messages.warning(self.request, 'Warning: Hello')
        # messages.debug(self.request, 'Debug: Hello')
        # messages.success(self.request, 'Success: Hello')
        return context

class ContactPageView(TemplateView):
    template_name = 'mtplus/contact.html'
    
class FaqPageView(TemplateView):
    template_name = 'mtplus/faq.html'

class FormsetUpdateView(UpdateView):
    formset_class = None

    def get_formset_class(self):
        """
        Returns the formset class to use in this view
        """
        return self.formset_class

    def get_formset(self, formset_class=None):
        """
        Returns an instance of the formset to be used in this view.
        """
        if formset_class is None:
            formset_class = self.get_formset_class()
        return formset_class(**self.get_form_kwargs())

    def get(self, request, *args, **kwargs):
        if self.get_object() is not None:
            self.object = self.get_object()
        form = self.get_form()
        formset = self.get_formset()

        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def post(self, request, *args, **kwargs):
        if self.get_object() is not None:
            self.object = self.get_object()
        form = self.get_form()
        formset = self.get_formset()
        print('form is valid = %s' % form.is_valid)
        print('formset is valid = %s' % formset.is_valid)
        if form.is_valid():
            print('Form is valid')
        if formset.is_valid():
            print("Formset is valid")

        if form.is_valid() and formset.is_valid():
            print('forms and formset is valid   ')
            return self.forms_valid(form, formset)

        return self.forms_invalid(form, formset)

    def forms_valid(self, form, formset):
        """
        Called if all forms are valid. Creates a Author instance along
        with associated books and then redirects to a success page.
        """
        print('valid form')
        self.object = form.save()
        formset.instance = self.object
        savedobjects = formset.save()
        # savedobjects.save()

        return HttpResponseRedirect(self.get_success_url())

    def forms_invalid(self, form, formset):
        """
        Called if whether a form is invalid. Re-renders the context
        data with the data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def get_context_data(self, **kwargs):
        """ Add formset and formset to the context_data. """
        ctx = super(FormsetUpdateView, self).get_context_data(**kwargs)

        if self.request.POST:
            ctx['formset'] = self.get_formset()
        else:
            ctx['formset'] = self.get_formset()

        return ctx


# class FormsetCreateView(FormsetUpdateView):
#     def get_object(self, queryset=None):
#         return None

mtplus/templates/mtplus/partials/alert_messages.html
{% load string_filters %}
{% if messages %}
    <div id="messages" class="row" >
    {% for message in messages %}
    <div  class="alert {% for tag in message.tags|split %}alert-{% if tag == 'error' %}danger{% else %}{{ tag }}{% endif %} {% endfor %} fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="alertinner {% if 'noicon' not in message.tags %}wicon{% endif %}">
            {# Allow HTML to be embedded in messages #}
            {% if 'safe' in message.tags %}
                {{ message|safe }}
            {% else %}
                {{ message }}
            {% endif %}

            {% if 'noicon' not in message.tags %}
                {# Include an icon by default #}
                {% if 'success' in message.tags %}
                    <i class="icon-ok-sign"></i>
                {% elif 'info' in message.tags %}
                    <i class="icon-info-sign"></i>
                {% elif 'warning' in message.tags %}
                    <i class="icon-warning-sign"></i>
                {% elif 'danger' in message.tags or 'error' in message.tags %}
                    <i class="icon-exclamation-sign"></i>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% endfor %}
    </div>
{% endif %}


mtplus/templates/mtplus/partials/breadcrumb.html
{% load i18n %}
{#  {% block breadcrumbs %}#}
      <div class="row wrapper border-bottom white-bg page-heading">
          <div class="col-lg-10">
              <h2>{% block breadcrumbs_title %}{% endblock %}</h2>
              <ol class="breadcrumb">
                  <li>
                      <a href="/">{% trans 'Home' %}</a>
                  </li>
              {% block breadcrumbs_sub %}{% endblock %}
                  <li class="active">
                      <strong>{% block breadcrumbs_current_title %}{% endblock %}</strong>
                  </li>
              </ol>
          </div>
          <div class="col-lg-2">

          </div>
      </div>
{#  {% endblock %}#}

mtplus/templates/mtplus/partials/footer.html
{% load i18n %}
<div class="footer">
    <div class="pull-right">
        &nbsp;
    </div>
    <div>
        <strong>Copyright</strong> Market+ &copy; 2017
    </div>
</div>

mtplus/templates/mtplus/partials/navigation.html
{% load i18n %}
{% load staticfiles %}
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                            <img alt="image" class="img-circle" src="{% static "mtplus/img/profile_small.jpg" %}"/>
                    </span>

                     <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{user.get_full_name}}</strong>
                             </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>

                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url "customer:profile"  %}">{% trans 'Profile' %}</a></li>
                        <li><a href="{% url "account_settings"  %}">{% trans "Settings" %}</a></li>
                        <li><a href="{% url "account_password"  %}">{% trans "Change password" %}</a></li>
                        <!-- <li><a href="contacts.html">Contacts</a></li> -->
                        <!-- <li><a href="mailbox.html">Mailbox</a></li> -->
                        <li class="divider"></li>
                        <li><a href="{% url "account_logout"  %}">{%  trans 'Logout' %}</a></li>
                    </ul>

                </div>
                <div class="logo-element">
                    MT+
                </div>
            </li>
            <li>
                <a href="{% url "customer:company"  %}"><i class="fa fa-institution"></i> <span class="nav-label">{% trans 'Company' %}</span></a>
            </li>
{#            <li >#}
{#                <a href="{% url "customer:files"  %}"><i class="fa fa-cloud"></i> <span class="nav-label">{% trans 'Company files' %}</span></a>#}
{#            </li>#}
            <li>
                <a href="{% url "customer:employee_list" %}"><i class="fa fa-users"></i> <span class="nav-label">{% trans 'Employees' %}</span> </a>
            </li>
             <li>
                <a href="{% url "customer:product_list" %}"><i class="fa fa-cubes"></i> <span class="nav-label">{% trans 'My products' %}</span> </a>
            </li>
            <li>
                <a href="{% url "customer:order_list" %}"><i class="fa fa-pencil-square-o"></i> <span class="nav-label">{% trans 'Orders' %}</span> </a>
            </li>
            <li>
                <a href="{% url "customer:site_index" path="customer/chat.html" %}"><i class="fa fa-comments"></i> <span class="nav-label">{% trans 'Chat' %}</span> </a>
            </li>

        </ul>

    </div>
</nav>

mtplus/templates/mtplus/partials/topnavbar.html
{% load i18n staticfiles %}
<div class="row border-bottom white-bg">
     <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            {% if user.is_authenticated %}
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            {% else %}
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                <a href="{% url "home" %}" class="navbar-brand">Market+</a>
            {% endif %}
        </div>
        <div class="navbar-collapse collapse" id="navbar">
              <ul class="nav navbar-top-links navbar-right">
                <!-- <li class="dropdown">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Pages' %} <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{% url "customer:index" %}">{% trans 'Products' %}</a></li>
                            <li><a href="">{% trans 'Faq' %}</a></li>
                            <li><a href="">{% trans 'Contact' %}</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Information <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="">Blogs</a></li>
                            <li><a href="">FAQ</a></li>
                            <li><a href="">Menu item</a></li>
                            <li><a href="">Menu item</a></li>
                        </ul>
                    </li>

                </ul> -->
                    <li>
                        <a href="{% url 'customer:index' %}"><i class="fa fa-cubes"></i> {% trans "Products" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'faq' %}"><i class="fa fa-question"></i> {% trans "Faq" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'contact' %}"><i class="fa fa-phone"></i> {% trans "Contact" %}</a>
                    </li>



             {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'customer:summary' %}"><i class="fa fa-user"></i> {% trans "Account" %}</a>
                    </li>
                    {% if user.is_staff %}
                        <li><a href="{% url 'admin:index' %}"><i class="fa fa-list-ul"></i> {% trans "Admin panel" %}</a></li>
                    {% endif %}
                    <li><a id="logout_link" href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> {% trans "Logout" %}</a></li>
                {% else %}
                    <li><a id="login_link" href="{% url 'account_login' %}"><i class="fa fa-sign-in"></i> {% trans "Login" %}</a></li>
                    <li><a id="login_link" href="{% url 'account_signup' %}"><i class="fa fa-registered"></i> {% trans "Register" %}</a></li>
                {% endif %}
              {% get_current_language as LANGUAGE_CODE %}
              {% get_language_info for LANGUAGE_CODE as lang_info %}
              {% get_available_languages as LANGUAGES %}
              {% static "mtplus/img/lang" as baseLangImg %}
                  <li class="dropdown">
{#                      {% for lang in LANGUAGES %}#}
{#                          {% if lang.0 == LANGUAGE_CODE %}#}
                              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                  <img src="{{ baseLangImg }}/{{ lang_info.code }}.png"/> {{ lang_info.name_local }} ({{ lang_info.code }})
                                  <span class="caret"></span>
                                </a>
{#                          {% endif %}#}
{#                      {%  endfor %}#}
                  <ul class="dropdown-menu pull-right" role="menu">
                  {% for lang in LANGUAGES %}
                          {% if lang.0 != LANGUAGE_CODE %}
                              <li role="presentation"><a role="menuitem" tabindex="1" href="#" onclick="changeLanguage('{{lang.0}}')">
                                     <img src="{{ baseLangImg }}/{{ lang.0 }}.png"/> {{ lang.1 }} ({{ lang.0 }})</a></li>
                          {% endif %}
                      {%  endfor %}
                  </ul>
                  {% comment %}    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><img
                              src="{% static "mtplus/img/lang/en.png" %}"/> {% trans 'English' %}
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu pull-right" role="menu">
                          <li role="presentation"><a role="menuitem" tabindex="1" href="#" onclick="changeLanguage('uz')"><img
                                  src="{% static "mtplus/img/lang/uz.png" %}"/> {% trans 'Uzbek' %}</a></li>
                          <li role="presentation"><a role="menuitem" tabindex="2" href="#" onclick="changeLanguage('ru')"><img
                                  src="{% static "mtplus/img/lang/ru.png" %}"/> {% trans 'Russian' %}</a></li>
                      </ul>{% endcomment %}
                  </li>

              </ul>
        </div>
    </nav>
</div>
<form action="{% url 'account_change_lang' %}" method="post" id="langForm">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}"/>
    <input name="language" type="hidden" value="" id="languageId"/>
    {#                      <input name="language" type="hidden" value="{{ LANGUAGE_CODE }}" />#}
    {% comment %}{% get_available_languages as LANGUAGES %}
    <select name="language">



        {% for lang in LANGUAGES %}
            <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected"{% endif %}>
                {{ lang.1 }} ({{ lang.0 }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go"/>{% endcomment %}
</form>
<script>
    function changeLanguage(lang) {
        $('#languageId').val(lang);
        $('#langForm').submit();
    }

    </script>